language: java
script: echo "Deploying"
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
env:
  global:
  - secure: i3rRXWvMw9Q7+dYvuwPi17HHnQR3aFULxPG/6qEwAkbIKs6IlbI4bw4CrGpjECYH9XImmB0WsIFIGvO2fZL/Wpp8QrwvHiDImhTH93qlWYLo/dqZvIyW5NrnbzcLKygKpRWxuqvlbyiqsYruswG1IgUbT5icP0SHk4ICWlHo6UlFFvEQUZ0EikT2AY3LnivamPr18Dixpio5axvN9I2h7zkfeAZ0KaO34YvyOT1liJDS7tLxd2eztjlIB8u2fdnn7kV0vvwjh3hD+QrfT99ejATEj1BpC2rjkdX2p1qBx04L/pWSyK3k9y7wfsSizbmnRFrtUGjWYN4ucx+9D8zTsQ61up3eQQpcFMtRDCb1CQWukFaLOBOhH6isZKh/Pa55Oac/mPO0EcM8xs8u++6ZybGo4cmNx9G3dx1Fl5O4daisdVftcvXJZvHiDHrFRvH2ZiNRsySJugGSvQrQsrzSyWfXdJ63Ayw0J1Ol5WNYCykvFdj7tI0PruEXlh7npk5Upodc1ruK870l2Ag6ZlQ6CLUJR6O2eHl8pslXwobbiTwkUvEf3eOh8Y+3riJNb6sLnpSZw/HBi73roeRNSdESVC3TdpEjaLpOhKIEe8VSJQwK/ELVyoX8JxrvpvqABY6yqziLGNbdIMu0RngmoCS+qHBkeMdf+sIhivMnbkEWumE=
  - secure: dGqSNcJ0wCIVk9d2To2SRXAA/7Gtlw4eJ3uYBiW0lkGr1V9teD/X01uSOhDBvL55mw1VXrcNIyIZoNH+2QJLtcZxdlQpIM7l/4zFAskch+lKTP5mja85IT0FVUO98iO7qTlRO050mnlsU02kCBKtrYdefzOHwttSNXU9B0OHuNb8z29Vgi9+Ppf7NSeU2FyXaJ2oVCP+Rti4cVVirU8w2ZbEgNADmJ57CZkbR14xY+EJ+BXRNUiqAnkiuqrvbRLXJHSQzJzXaEKA5/xb1pzBBDlnBWn3HipjsBw7NqCrWkNt6UxzyX/wrpa70lpiGC0E9SdgMCcCg9vY7oIfS/IZHvvs95xkGWwgANzv8i9eurIT623xLvevE6CDS6QR5rw6m8aou0EwhreDzYxDai9GwSdcfHncEsNaVrUWdKsSVUPjwq+xmJcUEWSXo6GCufGQt+n2OQxOYtPYkwbbiM4zsbgRCB1M/bxZ77SUI9+tGJYyFsvrFG3hCMHfK5Zib8ylrDDTOAT0U8+Y8ewAPobk3fFBqPMVi4RsLgqaVwza5sEh+lWT/Z7AFD+7969XXpV6zQEn5Rj/buyJsU0ZO4/1uEK26t1doM01CJdHKoQpltcBRn/90qcg99ao6S8nvnZT/r3RGT4fQE5sCuiFZnJp2IDakzHMM75QmHGIJrR/xx8=
services:
- docker
deploy:
- provider: script
  script: bash docker-push.sh
  on:
    branch: master
